database:
    restart: always
    image: postgres:latest
    volumes:
        - pgdata:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: django
    ports:
        - 5432:5432
restapi:
    build: ./docker/api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./restapi:/django
    ports:
        - "8000:8000"
    links:
        - database
    environment:
        DEBUG: "true"
        DATABASE_NAME: django 
        DATABASE_USER: django
        DATABASE_PASSWORD: django
        DATABASE_SERVICE_HOST: database
client:
    build: ./docker/client
    volumes:
        - ./client:/client
    ports:
        - "80:3000"
    command: npm start

