# Use a lighter version of Node as a parent image
FROM mhart/alpine-node:8.11.4

# Set the working directory to /client
WORKDIR /client

# Make port 3000 available to the world outside this container
EXPOSE 3000

